### ISSUE TITLE
Filter option in nutrient info and conversion factor pages

### ISSUE THREAD

**Issue by rklutka** [BFSSI-Bioinformatics-Lab/nutrition_database#20]
Can we add 

Nutrient info page:
the option to filter on nutrients and nutrient symbols of interest in addition to sorting  

Conversion factor page:
the options to filter on measure description in addition to sorting

**Comment by ajverster** [comment]
I've added a search box that you can use to filter the results of the nutrients and conversion factors. It will be on the website tomorrow.
