### ISSUE TITLE
Error message when creating conversion factor

### ISSUE THREAD

**Issue by sdjef** [BFSSI-Bioinformatics-Lab/nutrition_database#27]
I clicked on: New database items -> Create conversion factors
Then selected:
- food code -> 26
- measure id -> 30ml
- conv factor -> 0.123
Then clicked: Submit 

This is the error page that was displayed: 

![Snap3](https://user-images.githubusercontent.com/61470191/75904373-194aaa00-5e11-11ea-8ef3-6497736e5a5f.jpg)

**Comment by ajverster** [comment]
This fix will be on the website tomorrow
