### ISSUE TITLE
Cannot edit food detail page

### ISSUE THREAD

**Issue by rklutka** [BFSSI-Bioinformatics-Lab/nutrition_database#28]
Tried changing food name and source codes, error message received below for each attempt.  Error message below.

Request Method: | POST
-- | --
http://192.168.1.25:8090/food_enter/update/2/
2.2.7
KeyError
'REASON_FOR_CHANGE'
/mnt/NutritionDB/nutrition_database/nutrition_db/food_enter/views.py in form_valid, line 83
/home/adrian/anaconda3/envs/nutrition_db/bin/python
3.7.6
['/mnt/NutritionDB/nutrition_database',  '/home/adrian/anaconda3/envs/nutrition_db/lib/python3.7/site-packages',  '/home/adrian/anaconda3/envs/nutrition_db/lib/python37.zip',  '/home/adrian/anaconda3/envs/nutrition_db/lib/python3.7',  '/home/adrian/anaconda3/envs/nutrition_db/lib/python3.7/lib-dynload',  '/mnt/NutritionDB/nutrition_database/nutrition_db',  '/mnt/NutritionDB/nutrition_database/nutrition_db']
Wed, 4 Mar 2020 17:45:26 +0000

**Comment by ajverster** [comment]
Fixed, will be on the website tomorrow.
