### ISSUE TITLE
Edit screen in nutrient info modifications

### ISSUE THREAD

**Issue by rklutka** [BFSSI-Bioinformatics-Lab/nutrition_database#29]
![Edit screen modifications](https://user-images.githubusercontent.com/60946856/75911590-ca574180-5e1d-11ea-9997-63ee39f79651.jpg)

I was able to change the food code while editing protein in food code 2 to food code 4.  This resulted in protein being removed from food code 2 and an duplicate entry for protein in food code 4.  Should not be able to duplicate any nutrients in the nutrient info page.

![Snap24](https://user-images.githubusercontent.com/60946856/75911508-ad227300-5e1d-11ea-8c11-1947aea7ef66.jpg)

**Comment by ajverster** [comment]
I've put a fix on this so that you can't edit important fields. Note that the boxes aren't greyed out and you seem to be able to edit them but it won't do anything to the database. This isn't a perfect fix but this is all going to change when we get the paid plugin anyway.
