### ISSUE TITLE
Adding nutrients to a new food

### ISSUE THREAD

**Issue by sdjef** [BFSSI-Bioinformatics-Lab/nutrition_database#30]
After we create a new food using 'New database item' -> 'Create food', we should be able to go to the 'Nutrient info' page and add information about each nutrient. 
Since we have over 100 nutrients to enter, we would rather not have to click on a button each time we want to 'add a nutrient'. Another way of doing this would be to have an empty table listing all the 'nutrients', 'nutrient symbol' and 'unit', then we can fill out the rest of the columns including 'value', 'standard error' and 'number of observations'.

**Comment by ajverster** [comment]
I've changed it so that when you create a new food it initializes it with the 195 nutrients but without filling out the value, std error, num observations. Then you can go to the nutrient page for your food and fill in the rest of the data. Change will be on the website tomorrow.
