### ISSUE TITLE
Unable to edit niacin (nicotinic acid preformed) in any foods tested. 

### ISSUE THREAD

**Issue by rklutka** [BFSSI-Bioinformatics-Lab/nutrition_database#31]
No error message is received when attempting to edit but green success message does not appear.   Have tried on multiple foods.  Is it possible to have a message such as "unsuccesful"?  It is hard to know if its just the computer being slow vs trying to do something you can't do.  This type of message would be useful in other pages as well.  

Is there a quick way for you to determine if all nutrients have been set to editable or should we try to edit each one to be sure?

**Comment by sdjef** [comment]
I tried editing all the nutrients in a food. I was able to edit every single one of the except for niacin (nicotinic acid) preformed.

**Comment by ajverster** [comment]
This was a problem with the triggers, which are now fixed.

I've also changed this so that you will see a red "error" message when the edit fails. This will be on the website tomorrow.
