### ISSUE TITLE
Revert to previous history function 

### ISSUE THREAD

**Issue by sdjef** [BFSSI-Bioinformatics-Lab/nutrition_database#32]
Under 'Nutrients associated with this food' -> select any nutrient and click on 'History'. 
I tried the function to revert to previous history (see image below), after having made previous edits to that particular nutrient.    

![image](https://user-images.githubusercontent.com/61470191/75920174-d72f6180-5e2c-11ea-8140-5de3c2b28ca6.png)

A pop up appeared (see below), and I clicked 'OK'. 

![image](https://user-images.githubusercontent.com/61470191/75920576-a996e800-5e2d-11ea-9cfb-066a9cf5f086.png)

The revert history function did not seem to work, because, in the nutrient info table, I could still see the newly edited nutrient values rather than the original values.

**Comment by ajverster** [comment]
This has been fixed
