### ISSUE TITLE
Fields to add to nutrient info 

### ISSUE THREAD

**Issue by rklutka** [BFSSI-Bioinformatics-Lab/nutrition_database#33]
Please add in the following fields in this order after num observations

source (SOURCE_C) NUTR_AMOUNT FILE
reference (REF_C) NUTR_AMOUNT FILE
entry date (DATE_ENTRY) NUTR_AMOUNT FILE
Usda source (USDA_SOURCE) NUTR_AMOUNT FILE
Usda derivation code (USDA_DERIVATION) NUTR_AMOUNT FILE
tagname (TAGNAME) NUTRIENT NAME FILE
publication (PUBLICATION_CODE) NUTR_AMOUNT FILE

**Comment by ajverster** [comment]
will be on the website tomorrow
