### ISSUE TITLE
Filter more than one column

### ISSUE THREAD

**Issue by MC-BNS** [BFSSI-Bioinformatics-Lab/nutrition_database#6]
Is it possible to filter for more than one column? For example when looking for "apple" could i filter by food code then by groupe code? Similar to Excel where you can apply one filter after another.

**Comment by ajverster** [comment]
I've changed it so that if you search in the main box with the word "apple" it finds products that contain "apple" and if you search in the group box with the word "apple" it searches for groups that contain the word "apple". Please let me know if this is sufficient.
