### ISSUE TITLE
Removal of filter on third click

### ISSUE THREAD

**Issue by MC-BNS** [BFSSI-Bioinformatics-Lab/nutrition_database#7]
When using the filter arrows... are we able to remove the filter up or down on the third click? Currently when you filter up or down you are not able to get back to the "original" view. E.g.

"Original" view
![image](https://user-images.githubusercontent.com/61424093/75187121-69da4d00-5717-11ea-9779-766e79281530.png)
 
Clicking on arrow once in the Nutrient column (changing the order of the view)
![image](https://user-images.githubusercontent.com/61424093/75187165-837b9480-5717-11ea-837d-68902a4925db.png)

Clicking on arrow for a 2nd time in the Nutrient column (changing the order of the view)
![image](https://user-images.githubusercontent.com/61424093/75187213-9c844580-5717-11ea-85ec-96620ee32ef7.png)

After that I am not able to get back to the "original" view. Is there a trick to do so?

**Comment by ajverster** [comment]
The third click is possible but right now its difficult. I've added a reset button that reverts to the original order. Please let me know if this is sufficient.
