### ISSUE TITLE
Missing hover over text on icon on Food detail page

### ISSUE THREAD

**Issue by MC-BNS** [BFSSI-Bioinformatics-Lab/nutrition_database#9]
Is it possible to add the description of what the icons represent on the following page to have as hover over text? 
![image](https://user-images.githubusercontent.com/61424093/75256791-05b89700-57b2-11ea-9d9a-06b8f7a4335b.png)

We have that feature already on the main page.

**Comment by ajverster** [comment]
Fixed.
